name       : wireplumber
version    : 0.4.7
release    : 5
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.7/wireplumber-0.4.7.tar.gz : 86831102281daa11075d4e0eaebf078a601b1c63339511ec6220100d2b21f10a
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
