name       : wireplumber
version    : 0.4.4
release    : 1
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.4/wireplumber-0.4.4.tar.gz : a09ef574990a39db134506079cc9abe76ab5931ea2bdbee8ac01023a9e6f3185
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
