name       : wireplumber
version    : 0.4.6
release    : 4
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.6/wireplumber-0.4.6.tar.gz : 3eb3ef519490b4c7b51712bc6e44bb4ba63f550c49654cfc8ad6c400eaa1aa2c
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
