name       : wireplumber
version    : 0.4.5
release    : 3
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.5/wireplumber-0.4.5.tar.gz : 73c76c8cd60d3f96e586122a13257586396d7e34b2f9ffad39d27015a1fa0a13
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %patch -p1 < $pkgfiles/replace-hash-on-new-insert.patch
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
