name       : wireplumber
version    : 0.4.9
release    : 8
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.9/wireplumber-0.4.9.tar.gz : 0b25774a2821286a1fa31afb7db8db0573f493b35c40a7031b6e5a30cec0bbe3
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
