name       : wireplumber
version    : 0.4.11
release    : 12
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.11/wireplumber-0.4.11.tar.gz : cf5df4e4d2ab5402b4ede3bfa8931ff758359a46b6676541faebf3055d5a1fc6
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
