name       : wireplumber
version    : 0.4.12
release    : 13
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.12/wireplumber-0.4.12.tar.gz : afece031dd2d1a5f535de29e21ea94a1b261d3da62b5dbb977e19668f4453b27
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
