name       : wireplumber
version    : 0.4.8
release    : 7
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.8/wireplumber-0.4.8.tar.gz : a7a84c21230c339a905704a9495dda10a4dec41a96bc115a9b33d24310a3f605
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %patch -p1 < $pkgfiles/backport-for-openal-steam-issues.patch
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
