name       : wireplumber
version    : 0.4.10
release    : 11
source     :
    - https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.10/wireplumber-0.4.10.tar.gz : bddc5bb3c47e97c170d27c712bc3c7912592aea1ea9df747e92685f5194456d4
license    : MIT
component  : multimedia.library
summary    : Session / policy manager implementation for PipeWire
description: |
    WirePlumber is a modular session / policy manager for PipeWire and a GObject-based high-level library that wraps PipeWire's API, providing convenience for writing the daemon's modules as well as external tools for managing PipeWire.
builddeps  :
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(lua)
    - doxygen
    - python-lxml
setup      : |
    %patch -p1 < $pkgfiles/property_default_to_true.diff
    %meson_configure -Dsystem-lua=true -Delogind=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
